version: "3"

services:
  backend:
    container_name: budget_backend_container
    expose:
      - 3001
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - "traefik.enable=true"
      - "traefik.http.routers.budget-backend.entrypoints=websecure"
      - "traefik.http.routers.budget-backend.rule=Host(`budget-api.sertay.com`)"
      - "traefik.http.routers.budget-backend.tls.certresolver=myresolver"
      - "traefik.docker.network=traefik_network"
      - "traefik.http.services.budget-backend.loadbalancer.server.port=3001"
      # Enable CORS headers
      - "traefik.http.middlewares.budget-backend-cors.headers.accesscontrolallowmethods=GET,POST,PUT,DELETE,OPTIONS,PATCH"
      - "traefik.http.middlewares.budget-backend-cors.headers.accesscontrolalloworiginlist=https://budget.sertay.com"
      - "traefik.http.middlewares.budget-backend-cors.headers.accesscontrolallowcredentials=true"
      - "traefik.http.middlewares.budget-backend-cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.routers.budget-backend.middlewares=budget-backend-cors"
    image: ghcr.io/sertaykabuk/budget-management/backend:latest
    environment:
      NODE_ENV: production
      PORT: 3001
      DATABASE_URL: ${DATABASE_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      BACKEND_URL: ${BACKEND_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      AZURE_OPENAI_USE_API_KEY: ${AZURE_OPENAI_USE_API_KEY}
      AZURE_OPENAI_ENDPOINT: ${AZURE_OPENAI_ENDPOINT}
      AZURE_OPENAI_API_KEY: ${AZURE_OPENAI_API_KEY}
      AZURE_OPENAI_DEPLOYMENT_NAME: ${AZURE_OPENAI_DEPLOYMENT_NAME}
      JWT_SECRET: ${JWT_SECRET}
      MAX_FILE_SIZE: ${MAX_FILE_SIZE}
      UPLOAD_DIR: ${UPLOAD_DIR}
    volumes:
      - backend-uploads:/app/uploads
    networks:
      - db_network
      - traefik_network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: budget-frontend-prod
    restart: unless-stopped
    environment:
      - VITE_API_URL=${BACKEND_URL}
      - VITE_WS_URL=${BACKEND_WS_URL}
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - "traefik.enable=true"
      - "traefik.http.routers.budget-frontend.entrypoints=websecure"
      - "traefik.http.routers.budget-frontend.rule=Host(`budget.sertay.com`)"
      - "traefik.http.routers.budget-frontend.tls.certresolver=myresolver"
      - "traefik.docker.network=traefik_network"
      - "traefik.http.services.budget-frontend.loadbalancer.server.port=80"
    image: ghcr.io/sertaykabuk/budget-management/frontend:latest
    networks:
      - traefik_network
    depends_on:
      - backend

networks:
  db_network:
    external: true
  traefik_network:
    external: true

volumes:
  backend-uploads:
    driver: local
