version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    container_name: budget-traefik-local
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - budget-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: budget-backend-local
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
      - PORT=3001
      - BACKEND_URL=http://backend.localhost
      - FRONTEND_URL=http://frontend.localhost
    volumes:
      - backend-uploads:/app/uploads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend.localhost`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=3001"
    networks:
      - budget-network
    depends_on:
      - traefik

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://backend.localhost
        - VITE_WS_URL=ws://backend.localhost
    container_name: budget-frontend-local
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend.localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    networks:
      - budget-network
    depends_on:
      - backend
      - traefik

networks:
  budget-network:
    driver: bridge

volumes:
  backend-uploads:
    driver: local
